# Uncomment the next line to define a global platform for your project
platform :ios, '12.3'

target 'iDine' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iDine
  pod 'BraintreeDropIn'

  target 'iDineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iDineUITests' do
    # Pods for testing
  end

end
